-- Auto-generated by generate_category_runner.py
module Problems.Arrays.Arrays (arrays) where

import Problems.Arrays.CountSymmetricInts (doCountSymmetricInts)
import Problems.Arrays.RemoveDuplicatesFromSortedArray (doRemoveDuplicatesFromSortedArray)

arrays :: IO ()
arrays = do
  putStrLn "\n--- Arrays Problems ---"
  doCountSymmetricInts
  doRemoveDuplicatesFromSortedArray
